# air.toml - Live reload configuration for Meshgate development

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Control plane configuration
  args_bin = []
  bin = "./tmp/control-plane.exe"
  cmd = "go build -o ./tmp/control-plane.exe ./control-plane"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "dist", "data", "logs", "certs", ".git", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["control-plane"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

# Environment variables for development
[[build.env]]
  name = "DB_PATH"
  value = "./data/meshgate-dev.db"

[[build.env]]
  name = "PORT"
  value = "8080"

[[build.env]]
  name = "LOG_LEVEL"
  value = "debug"

[[build.env]]
  name = "JWT_SECRET"
  value = "dev-secret-change-in-production"

# Optional: Uncomment to enable TLS in development
# [[build.env]]
#   name = "TLS_CERT_FILE"
#   value = "./certs/server.crt"

# [[build.env]]
#   name = "TLS_KEY_FILE"
#   value = "./certs/server.key"